version: '3.3'
services:
  database:
    image: 'mysql:5.7.40'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
      - MYSQL_USER=dxpcloud
      - MYSQL_PASSWORD=hello_world
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    ports:
      - 3306:3306
    volumes:
      - './volumes/database/data:/var/lib/mysql'

  liferay:
    image: 'liferay/dxp:7.4.13-u86'
    environment:
      - LIFERAY_JVM_OPTS=-Xms4g -Xmx4g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_lass_UPPERCASEN_ame=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/lportal?dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useSSL=false&allowPublicKeyRetrieval=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=dxpcloud
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=hello_world
    ports:
      - 8000:8000
      - 8080:8080
      - 11311:11311
    volumes:
      - ./docker-compose/liferay/scripts:/mnt/liferay/scripts
      - ./bundles/deploy:/mnt/liferay/deploy
      - ./bundles/data/document_library:/opt/liferay/data/document_library
      - ./bundles/osgi/modules:/opt/liferay/osgi/modules
      - ./bundles/osgi/configs:/opt/liferay/osgi/configs
      - ./bundles/osgi/war:/opt/liferay/osgi/war
      - ./bundles/logs:/opt/liferay/logs
    depends_on:
      search:
         condition: service_healthy
      database:
         condition: service_started

  search:
    image: 'elasticsearch:7.16.3'
    environment:
      - "discovery.type=single-node"
      - "node.name=es-node1"
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=liferay_cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    init: true
    command: >
      sh -c "
      cd /usr/share/elasticsearch/bin;
      if [ ! -d '/usr/share/elasticsearch/plugins/analysis-icu' ]; then ./elasticsearch-plugin install analysis-icu; fi;
      if [ ! -d '/usr/share/elasticsearch/plugins/analysis-kuromoji' ]; then ./elasticsearch-plugin install analysis-kuromoji; fi;
      if [ ! -d '/usr/share/elasticsearch/plugins/analysis-smartcn' ]; then ./elasticsearch-plugin install analysis-smartcn; fi;
      if [ ! -d '/usr/share/elasticsearch/plugins/analysis-stempel' ]; then ./elasticsearch-plugin install analysis-stempel; fi;
      /usr/local/bin/docker-entrypoint.sh;
      "
    volumes:
      - './volumes/search/data:/usr/share/elasticsearch/data'
    healthcheck:
       test: ["CMD-SHELL", "curl http://localhost:9200/_cluster/health | grep -qiE 'green|yellow'"]
       interval: 5s
       timeout: 5s
       start_period: 20s
       retries: 20
